Add Proceso para Planificar
novaDepto/Nova pull request #10
Opened 2020-09-29 19:56 UTC by marlagr

2020-09-29 19:58 UTC, AlonsoOropeza requested changes

2020-09-29 19:58 UTC, AlonsoOropeza commented on Proceso-para-Planificar.md
> +- [ ] jopc
Quita esto porfa

2020-09-29 19:59 UTC, marlagr commented on Proceso-para-Planificar.md
> +- [ ] jopc
okey, so linea 52

2020-09-29 20:07 UTC, AlonsoOropeza approved these changes
muy bien! :D

2020-09-30 20:22 UTC, peterglezroa requested changes
Lo veo súper bien. Sólo que por el markdown se deforma en una parte jejeje

2020-09-30 20:22 UTC, peterglezroa commented on Proceso-para-Planificar.md
> +    3.4. Enrolarse en las tareas
Aquí se deforma por el markdown. Creo que no tienes que poner el `3.*`, si no sólo poner `1.`, `2.`, etc

2020-10-01 14:34 UTC, marlagr commented on Proceso-para-Planificar.md
> +    3.4. Enrolarse en las tareas
Cierto, ya esta cubierto

2020-10-01 15:08 UTC, peterglezroa approved these changes
Súper 👍 😄

2020-10-01 15:08 UTC, merged