Update Politica-de-Comunicacion.md
novaDepto/Nova pull request #121
Opened 2020-10-23 19:22 UTC by LisieuxS

política para comunicar procesos añadida

2020-10-23 19:31 UTC, marlagr commented on Politica-de-Comunicacion.md
> +            </li>
En el Nova WOW ya viene cómo hacer esto

2020-10-23 20:07 UTC, ErwinAndresJL requested changes

2020-10-23 20:07 UTC, ErwinAndresJL commented on Politica-de-Comunicacion.md
> +          <li><b><i>nova-general</i></b>: Sirve para hacer anuncios/preguntas/encuestas departamentales.
Quitar las diagonales y mejor separarlos por comas para mejor redactado

2020-10-23 20:07 UTC, ErwinAndresJL commented on Politica-de-Comunicacion.md
> +          <li><b><i>nova-foro</i></b>: Inicia hilos de discusión/debate de temas departamentales.
Para estandarizarlo con el de arriba, pondría: "Sirve para iniciar hilos..." y quitar la diagonal invertida, no sé si eso significa "y" u "o".

2020-10-23 20:07 UTC, ErwinAndresJL commented on Politica-de-Comunicacion.md
> +          <li><b><i>Grupo de Whatsapp</i></b>: Se utiliza únicamente para mensajes <a href="#glosario1">reactivos</a>.
el link de reactivos no lleva a nada cuando doy click, si no mejor quitarlo

2020-10-23 20:07 UTC, ErwinAndresJL commented on Politica-de-Comunicacion.md
> +             <b>NOTA: </b>En caso de tener un anuncio <a href="#glosario2">urgente</a> el mensaje será enviado por Slack y se notificara a los miembros de su urgencia en el grupo de Whatsapp mediante
el link de urgente tampoco sirve

2020-10-23 20:09 UTC, ErwinAndresJL requested changes
En el glosario le falta el acento a "únicamente" y a "están", además el uso de diagonales deja confuso la descripción, mejor quitarlas redactarlo mejor.

2020-10-28 20:11 UTC, marlagr approved these changes

2020-10-28 21:52 UTC, DanElias approved these changes

2020-10-29 00:07 UTC, DanElias commented
@ErwinAndresJL Creo que ya está corregido

2020-10-29 20:43 UTC, ErwinAndresJL approved these changes

2020-10-29 20:53 UTC, closed without merging

2020-10-29 20:53 UTC, DanElias commented
obsoleto