Update Proceso-de-inicio-de-iteración.md
novaDepto/Nova pull request #129
Opened 2020-10-25 21:20 UTC by Raylogic

2020-10-25 22:53 UTC, DanElias approved these changes

2020-10-26 01:52 UTC, ErwinAndresJL approved these changes

2020-10-26 01:57 UTC, ErwinAndresJL requested changes

2020-10-26 01:57 UTC, ErwinAndresJL commented on Proceso-de-inicio-de-iteración.md
> +      <td>Identifica los riesgos de la iteración siguendo el <strong><a href="https://github.com/novaDepto/Nova/blob/master/Proceso-de-gesti%C3%B3n-de-riesgos">Proceso de Gestión de Riesgos.</a></str
Lo veo muy bien. solo falta poner el link correcto del proceso de gestión de riesgos :)

2020-10-27 20:42 UTC, marlagr approved these changes

2020-10-29 00:08 UTC, DanElias commented
@Raylogic Falta arreglar el link roto de gestión de riesgos

2020-10-29 20:43 UTC, ErwinAndresJL approved these changes

2020-10-29 20:48 UTC, merged