Descripción en el nombre
novaDepto/Nova pull request #13
Opened 2020-10-01 00:30 UTC by LisieuxS

institucionalización suena suficiente pero me andaban preguntando por la guía del pull request así que tal vez no era tan descriptivo

2020-10-01 15:06 UTC, peterglezroa requested changes
Va. También tienes que cambiar el nombre del archivo y el archivo de la _sidenav para que se despliegue el título correctamente en todos lados. Si me da tiempo en un rato lo hago

2020-10-03 07:35 UTC, AlejandroMinaya approved these changes

2020-10-08 19:29 UTC, peterglezroa requested changes

2020-10-08 19:29 UTC, peterglezroa commented on Guía-para-institucionalizar-procesos-guías-políticas.md
>  El objetivo de esta guía es **orientar** y **facilitar** la participación en el
No me gusta

2020-10-09 19:43 UTC, closed without merging

2020-10-09 19:43 UTC, DanElias commented
Holi Lisieux, voy a cerrar este pull request porque ya pasaron varios días, pero si quieres hacer los cambios me dices para que los hagamos.