Update Guía-de-entorno-de-verificación.md
novaDepto/Nova pull request #175
Opened 2020-11-10 19:50 UTC by Raylogic

2020-11-11 15:20 UTC, DanElias requested changes
@Raylogic aquí tengo duda, solo se está estableciendo para el pair review e inspecciones pero creo que hay muchos más tipos, creo que sería bueno incluir una general que explique como establecer el entorno de verificación para cualquier tipo de verificación, además de para esas dos

2020-11-13 00:06 UTC, ErwinAndresJL requested changes
El link que está en el documento lleva a un docuemto eliminado

2020-11-23 04:13 UTC, DanElias reviewed
En espera de los cambios mencionados por Erwin

2020-11-25 15:15 UTC, DanElias commented
@Raylogic Ya no se harán cambios?

2020-11-27 03:56 UTC, ErwinAndresJL commented
No cerrar este pull request, se incorporará las corrección en otro pull request

2020-11-27 08:41 UTC, closed without merging

2020-11-27 08:41 UTC, DanElias commented
se incorporará las corrección en otro pull request