Update Proceso-para-institucionalizar-procesos-guías-y-políticas.md
novaDepto/Nova pull request #180
Opened 2020-11-11 08:29 UTC by Raylogic

2020-11-11 14:16 UTC, ErwinAndresJL approved these changes

2020-11-11 16:01 UTC, DanElias requested changes
@Raylogic Link roto en política de comunicación. Recuerden que si cambian el nombre del archivo se mueren todos los links que referenciaban ese archivo y hay que volver a verificar todos los archivos de la wiki, si cambian el título hay que cambiar la referencia a ese documentos en TODOS los archivos de la wiki.

2020-11-11 16:44 UTC, Raylogic commented
> @Raylogic Link roto en política de comunicación. Recuerden que si cambian el nombre del archivo se mueren todos los links que referenciaban ese archivo y hay que volver a verificar todos los archivos de la wiki, si cambian el título hay que cambiar la referencia a ese documentos en TODOS los archivos de la wiki.

Listo, arreglado, apruebe PLOX

2020-11-13 00:36 UTC, ErwinAndresJL commented
@DanElias ya se arregló el link

2020-11-13 16:29 UTC, DanElias approved these changes

2020-11-13 16:29 UTC, merged