Update Proceso-de-mejora-continua.md
novaDepto/Nova pull request #182
Opened 2020-11-11 11:15 UTC by Raylogic

2020-11-11 14:11 UTC, ErwinAndresJL approved these changes

2020-11-11 16:16 UTC, DanElias requested changes
@Raylogic @ErwinAndresJL MMM por qué se quitó los 3 puntos de mejora continua y la referencia el proceso de mejora de procesos? ya no se va a usar ese proceso? Yo si pondría los 3 principios de mejora continua. Por qué se quitaron todas las referencias a los archivos de CM? Por qué se quitaron todas las referencias a las políticas del departamento? Falta poner link al backlog de mejoras. La versión de Erwin se me hacia mejor

2020-11-11 16:58 UTC, Raylogic commented
> @Raylogic @ErwinAndresJL MMM por qué se quitó los 3 puntos de mejora continua y la referencia el proceso de mejora de procesos? ya no se va a usar ese proceso? Yo si pondría los 3 principios de mejora continua. Por qué se quitaron todas las referencias a los archivos de CM? Por qué se quitaron todas las referencias a las políticas del departamento? Falta poner link al backlog de mejoras. La versión de Erwin se me hacia mejor

Listo, corregido, apruebe PLOX

2020-11-11 23:27 UTC, LisieuxS approved these changes

2020-11-11 23:29 UTC, LisieuxS approved these changes

2020-11-12 16:50 UTC, DanElias approved these changes

2020-11-12 16:50 UTC, merged