Especificacion Reqm/Compromisos Daily Meeting
novaDepto/Nova pull request #185
Opened 2020-11-11 14:49 UTC by A01700043

2020-11-11 15:03 UTC, ErwinAndresJL approved these changes

2020-11-11 15:46 UTC, StarNiGHTS64 approved these changes

2020-11-11 16:23 UTC, DanElias requested changes
La tabla está rota, sale hasta el final del documento

2020-11-11 16:24 UTC, DanElias commented
@A01700043

2020-11-12 16:47 UTC, DanElias requested changes
Link roto en Proceso de ejecución de medidas correctivas. El checklist de institucionalización específica claramente que se deben de revisar todos los links y dejar de romperlos. @Raylogic

2020-11-13 00:39 UTC, ErwinAndresJL requested changes
Además en la parte de sintaxis, la primera actividad del proceso le falta punto final.

2020-11-19 04:27 UTC, DanElias requested changes
sigue roto el link de proceso de acciones correctivas

2020-11-23 04:24 UTC, DanElias approved these changes
@ErwinAndresJL Ya arreglé lo que faltaba para darle velocidad

2020-11-23 14:56 UTC, ErwinAndresJL approved these changes

2020-11-23 14:56 UTC, merged