Add proceso Daily Meeting
novaDepto/Nova pull request #19
Opened 2020-10-03 02:18 UTC by marlagr

Proceso para Verificar el cumplimiento del objetivo para el Daily Meeting

2020-10-05 16:40 UTC, AlejandroMinaya reviewed
@marlagr ahí te deje algunos comentarios, no sé si has tenido el chance de
verlos

2020-10-05 16:40 UTC, AlejandroMinaya commented on Proceso-de-Daily-Meeting.md
> + 1. Visualización del taskboard con items de trabajo
Aquí no se si valga la pena de cambiarlo a _Visualizar_ para que sea una oración imperativa.

2020-10-05 16:40 UTC, AlejandroMinaya commented on Proceso-de-Daily-Meeting.md
> +1. El eje horizontal del BurnDown Chart muestra los dias que abarca el plan de la iteración.
Aquí no sé si esto se métricas debería estar mas enfocado a medir el proceso. Tipo: duración de la junta. Para recolectar información que nos ayude a mejorar el proceso en si

2020-10-05 16:54 UTC, peterglezroa requested changes
De mi lado sólo te pediría que le quites el título para que no se duplique y que agregues el link para la sidenav

2020-10-05 16:54 UTC, peterglezroa commented on Proceso-de-Daily-Meeting.md
> +# Proceso de Daily Meeting
Hay que quitar este título para que en la wiki no se repita. Github automáticamente pone el título del archivo como el título del documento

2020-10-05 17:22 UTC, AlonsoOropeza requested changes
Igual que los demás el titulo se pone solito

2020-10-07 21:56 UTC, marlagr commented on Proceso-de-Daily-Meeting.md
> +1. El eje horizontal del BurnDown Chart muestra los dias que abarca el plan de la iteración.
Cierto 😬 👍

2020-10-07 21:57 UTC, marlagr commented on Proceso-de-Daily-Meeting.md
> +# Proceso de Daily Meeting
Va va 👍

2020-10-08 14:08 UTC, peterglezroa approved these changes
:+1:

2020-10-09 20:44 UTC, Yaf98 approved these changes

2020-10-09 20:47 UTC, Yaf98 approved these changes

2020-10-09 20:53 UTC, AlonsoOropeza approved these changes

2020-10-09 21:03 UTC, merged