Update Proceso-de-acciones-correctivas.md
novaDepto/Nova pull request #195
Opened 2020-11-16 03:57 UTC by Raylogic

2020-11-16 05:02 UTC, marlagr approved these changes

2020-11-16 19:57 UTC, ErwinAndresJL requested changes
Está bien que se haya movido a otra plantilla las acciones correctivas, en la plantilla me parece que hay cosas que no quedan claras, como seguridad, fluidez y rapidez. No queda claro por qué ponerle baja media o alta a cada una. También creo que hace falta un responsable de la medida correctiva.

2020-11-16 19:58 UTC, Raylogic commented
> Está bien que se haya movido a otra plantilla las acciones correctivas, en la plantilla me parece que hay cosas que no quedan claras, como seguridad, fluidez y rapidez. No queda claro por qué ponerle baja media o alta a cada una. También creo que hace falta un responsable de la medida correctiva.

La Plantilla tiene una tabla explicando el grado de cada criterio.

2020-11-16 20:00 UTC, Raylogic commented
> > Está bien que se haya movido a otra plantilla las acciones correctivas, en la plantilla me parece que hay cosas que no quedan claras, como seguridad, fluidez y rapidez. No queda claro por qué ponerle baja media o alta a cada una. También creo que hace falta un responsable de la medida correctiva.
> 
> La Plantilla tiene una tabla explicando el grado de cada criterio.
> La otra es cambiar los criterios para aceptar acciones correctivas, pero cuáles pueden ser entonces?

2020-11-17 17:12 UTC, ErwinAndresJL reviewed
Ok, ya vi la tabla, está bien eso entonces. Lo de los criterios ahora que entiendo veo que es para ver si se acepta o no. Este proceso ya estaba bien en PMC, y si se hace un cambio estaría bien que pusieras qué se pretende mejorar o qué es lo que estaba mal para entender mejor la razón del cambio. Ya solo te pediría que haya un responsable de la acción correctiva

2020-11-17 22:03 UTC, Raylogic commented
> Ok, ya vi la tabla, está bien eso entonces. Lo de los criterios ahora que entiendo veo que es para ver si se acepta o no. Este proceso ya estaba bien en PMC, y si se hace un cambio estaría bien que pusieras qué se pretende mejorar o qué es lo que estaba mal para entender mejor la razón del cambio. Ya solo te pediría que haya un responsable de la acción correctiva

Es que en PP nos pidieron que hubiera criterios para evaluar una acción correcctiva

2020-11-17 22:05 UTC, Raylogic commented
> > Ok, ya vi la tabla, está bien eso entonces. Lo de los criterios ahora que entiendo veo que es para ver si se acepta o no. Este proceso ya estaba bien en PMC, y si se hace un cambio estaría bien que pusieras qué se pretende mejorar o qué es lo que estaba mal para entender mejor la razón del cambio. Ya solo te pediría que haya un responsable de la acción correctiva
> 
> Es que en PP nos pidieron que hubiera criterios para evaluar una acción correcctiva

También ya implementé el campo 'Responsable' como paso en el proceso y la plantilla

2020-11-18 15:54 UTC, ErwinAndresJL approved these changes

2020-11-18 15:54 UTC, merged