Update and rename Proceso-para-plan-de-Involucramiento-de-Stakeholder…
novaDepto/Nova pull request #197
Opened 2020-11-16 07:26 UTC by Raylogic

…s.md to Proceso-de-Involucramiento-de-stakeholders.md

2020-11-16 16:03 UTC, DanElias requested changes
@LisieuxS @ErwinAndresJL @marlagr Se hicieron estos cambios, los aprueban? @Raylogic recuerda que hay un proceso de mejora de procesos, el primer paso es consultar al dueño del proceso y decirle los cambios propuestos. No hay que cambiar plantillas a lo loco sin gestionar el cambio. Ahora el proceso anterior ya no queda con la plantilla porque solo la plantilla se modifico pero el proceso aún no. Además, este proceso ya estaba bien, solo hacía falta ejecutarlo. De nada sirve perder nuestro tiempo primero rehaciendo cosas que ya están, y segunda perdiendo el tiempo de los demás revisando cosas que ya estaban

2020-11-20 15:35 UTC, DanElias requested changes
Sigue siendo válido mi comentario anterior, nose si Erwin o Lisi ya lo revisaron y entendieron los cambios que hiciste. Los POs ya también estaba ejecutando este proceso con la plantilla anterior, sería bueno preguntarles. Además, no veo la sidebar modificada para que tenga el nuevo nombre del documento. Estoy casi seguro que este documento se referenciaba en otros documentos por lo que se van a romper los links.

2020-11-23 04:26 UTC, DanElias reviewed
En espera de la retro de @ErwinAndresJL  o @LisieuxS y de los cambios en links en los demás documentos debido al cambio de nombre de este documento

2020-11-23 15:14 UTC, LisieuxS approved these changes

2020-11-23 15:16 UTC, LisieuxS commented
@StarNiGHTS64, @luisescobar8 , sólo si a ustedes les sirve

2020-11-23 15:17 UTC, LisieuxS requested changes
Mucho overhead

2020-11-23 15:31 UTC, ErwinAndresJL requested changes
No entiendo el cambio de este proceso, la mejora la debió de hacer quien ya lo ejecutó y notó cosas que estaban de más o cosas que faltaban. Checando los cambios me parece que tambn funciona. Antes de cualquier cambio se le debió avisar a Lisi para que esté conciente de cómo va a estar este proceso como dueñea del proceso.           De mi parte lo apruebo para darle agilidad, solo cambiar la versión del proceso, este ya sería la versión 1.1

2020-11-24 19:34 UTC, ErwinAndresJL approved these changes

2020-11-25 15:11 UTC, DanElias reviewed
@Raylogic ya no se van a hacer cambios? para darle close

2020-11-27 03:54 UTC, ErwinAndresJL commented
Esta plantilla ya se está utilizando en ambos equipos, por lo que ya debe aprobarse, recordar seguir el proceso de institucionalización. Solo queda la espera de los cambios en la sidebar y donde se referencía por el cambio de nombre que hubo.

2020-11-27 04:07 UTC, luisescobar8 commented
> ciona. Antes de

@ErwinAndresJL @LisieuxS @DanElias @marlagr De hecho yo tengo una propuesta de mejorar el proceso con la última plantilla disponible, sé que este proceso ya cumple con el scampi, es más de redacción ya que no entendía muy bien como usar la plantilla porque se creó una nueva,  Le agregué 2 campos a la plantilla que es el número de teléfono y correo electrónico, también el paso de agregar el plan de acciones al plan de la iteración. Haré un pull request agregando y si tienen pregunta me dicen XD

2020-11-27 08:42 UTC, DanElias commented
> > ciona. Antes de
> 
> @ErwinAndresJL @LisieuxS @DanElias @marlagr De hecho yo tengo una propuesta de mejorar el proceso con la última plantilla disponible, sé que este proceso ya cumple con el scampi, es más de redacción ya que no entendía muy bien como usar la plantilla porque se creó una nueva, Le agregué 2 campos a la plantilla que es el número de teléfono y correo electrónico, también el paso de agregar el plan de acciones al plan de la iteración. Haré un pull request agregando y si tienen pregunta me dicen XD

Entonces podemos cerrar este y aceptamos el tuyo Luis?

2020-11-27 23:10 UTC, closed without merging