Update and rename Proceso-Cierre-de-Iteracion.md to Proceso-de-cierre…
novaDepto/Nova pull request #198
Opened 2020-11-16 08:19 UTC by Raylogic

…-de-iteración.md

2020-11-16 15:51 UTC, DanElias requested changes
@Raylogic no hay que cambiar procesos que lalo ya nos dio visto bueno. Aparte de los cambios que he visto se están dejando muy MUY ambiguos los procesos tal es el caso de este que ya ni tiene sentido solo es una fase con dos tareas muy ambiguas. No aceptaré este cambio puesto que no tiene sentido cambiar procesos que ya están y más aún no tiene caso dejarlos aún más ambiguos

2020-11-20 15:30 UTC, DanElias requested changes
No veo el link de la sidebar actualizado al nuevo nombre. Cambiar acentos rompe links. No se hacía referencia a este proceso en otros documentos?

2020-11-23 04:29 UTC, DanElias reviewed
@Raylogic no se atendieron mis comentarios de revisar los links porque se agregó el acento. Lo haré yo porque ya pasaron varios días y no se atienden los comentarios. Pero tú debes ser el encargado de hacer esos cambios

2020-11-23 04:32 UTC, DanElias approved these changes

2020-11-23 14:57 UTC, ErwinAndresJL approved these changes

2020-11-23 14:57 UTC, merged