Add guia para definir un WBS
novaDepto/Nova pull request #20
Opened 2020-10-03 02:48 UTC by cmnb32

El objetivo de esta guia es dar las recomendaciones necesarias para definir un WBS. Forma parte del área de PP.

2020-10-05 16:42 UTC, AlejandroMinaya reviewed
@cmnb32 hey! Te dejé unos comentarios no sé si has tenido chance de verlos

2020-10-05 16:42 UTC, AlejandroMinaya commented on Guía-para-definir-un-WBS.md
> +3. Cada elemento del WBS debe ser un entregable __tangible__.
Siento que chance se pueden dejar ejemplos de que cuentan como entregables tangibles.

2020-10-05 17:23 UTC, AlonsoOropeza requested changes
el titulo se pone solito con el nombre del articulo

2020-10-05 17:24 UTC, AlonsoOropeza commented on Guía-para-definir-un-WBS.md
> +## Guía para definir un WBS
esta parte, lo demas todo bien

2020-10-05 20:16 UTC, peterglezroa requested changes

2020-10-05 20:16 UTC, peterglezroa commented on Guía-para-definir-un-WBS.md
> +## Guía para definir un WBS
Coincido con alonso

2020-10-05 20:16 UTC, peterglezroa commented on Guía-para-definir-un-WBS.md
> +
Yo quitaría la bitácora de cambios porque tenemos la herramienta de `git blame` y `git log` para revisaro todos los cambios

2020-10-08 01:13 UTC, luisescobar8 reviewed
Ando probando la sugestion, ignorenlo porfa :3

2020-10-08 01:13 UTC, luisescobar8 commented on Guía-para-definir-un-WBS.md
> +Orientar a la definición de __WBS efectivos__ que __cualquier miembro del
```suggestion
Orientar a la definición de __WBS efectivos__ que __cualquier miembro del (perdonen ando probando)
```
Probando la suggestion

2020-10-08 14:10 UTC, peterglezroa commented on Guía-para-definir-un-WBS.md
> +Orientar a la definición de __WBS efectivos__ que __cualquier miembro del
:eye: 👄 :eye:

2020-10-12 02:15 UTC, Yaf98 commented on Guía-para-definir-un-WBS.md
> +3. Cada elemento del WBS debe ser un entregable __tangible__.
- Tal vez se podría ser más especifíco en el punto 2 sobre cuales son esas actividades generales
- En el punto 3 coincido con Juanito, creo que está un poco ambiuguo

2020-10-12 02:23 UTC, Yaf98 requested changes

2020-10-12 02:23 UTC, Yaf98 commented on Guía-para-definir-un-WBS.md
> +3. Cada elemento del WBS debe ser un entregable __tangible__.
.

2020-10-12 15:37 UTC, cmnb32 commented on Guía-para-definir-un-WBS.md
> +## Guía para definir un WBS
Se ha eliminado

2020-10-12 15:43 UTC, marlagr approved these changes

2020-10-12 16:03 UTC, Yaf98 approved these changes

2020-10-13 03:50 UTC, DanElias commented
@AlonsoOropeza @peterglezroa Creo que ya quedo corregida, solo falta quitar los request changes para aprobar :)

2020-10-13 16:01 UTC, AlonsoOropeza approved these changes

2020-10-13 19:17 UTC, manu-yaff commented
@peterglezroa dale una checada a los requested changes cuando puedas

2020-10-14 02:10 UTC, DanElias approved these changes

2020-10-14 13:40 UTC, peterglezroa approved these changes

2020-10-14 13:41 UTC, merged