Create Proceso-de-Acompañamie-to-para-Competencia-Oral.md
novaDepto/Nova pull request #206
Opened 2020-11-18 20:06 UTC by LisieuxS

2020-11-19 15:55 UTC, ErwinAndresJL approved these changes

2020-11-20 04:56 UTC, ErwinAndresJL requested changes
El nombre del documento tiene error. Me aparece que está como "Acompañamie-to"

2020-11-23 04:35 UTC, DanElias approved these changes
@ErwinAndresJL Listo ya lo arreglé

2020-11-23 14:57 UTC, ErwinJulian approved these changes

2020-11-23 14:57 UTC, merged