Delete Proceso-de-mejora-de-procesos.md
novaDepto/Nova pull request #212
Opened 2020-11-19 17:43 UTC by Raylogic

2020-11-19 17:58 UTC, ErwinAndresJL approved these changes

2020-11-20 04:47 UTC, marlagr approved these changes

2020-11-20 15:16 UTC, DanElias requested changes
Se quitó de la sidebar?

2020-11-20 15:46 UTC, Raylogic commented
> Se quitó de la sidebar? No veo ninguna modificación al sidebar.md

Sí, lo eliminé cuando agregué las plantillas.

2020-11-23 04:43 UTC, DanElias approved these changes
@Raylogic no estaba cambiado. Ya lo cambié

2020-11-23 04:44 UTC, merged