Anadir Guia de Inconsistencias, Proceso Inicio
novaDepto/Nova pull request #222
Opened 2020-11-23 08:22 UTC by A01700043

2020-11-23 15:37 UTC, ErwinAndresJL requested changes
Se te fue una V en la línea 61. Faltan algunos puntos finales y creo que esta es la versión 1.2, si me puedes resolver esta duda por fa

2020-11-24 03:13 UTC, DanElias commented
> Se te fue una V en la línea 61. Faltan algunos puntos finales y creo que esta es la versión 1.2, si me puedes resolver esta duda por fa

Ya la arreglé. También estab roto el link a la guía de inconsistencias

2020-11-24 03:14 UTC, marlagr approved these changes

2020-11-24 03:14 UTC, DanElias approved these changes

2020-11-24 03:37 UTC, ErwinAndresJL approved these changes

2020-11-24 03:37 UTC, merged