Politica para manejo de datos v1.0
novaDepto/Nova pull request #23
Opened 2020-10-05 16:32 UTC by StarNiGHTS64

2020-10-05 16:50 UTC, peterglezroa commented on Politica-para-Manejo-de-Datos.md
> +Pendiente
No sé si sea mejor borrar esta parte en vez de dejarla como pendiente

2020-10-05 17:27 UTC, AlonsoOropeza requested changes
Coincido con Peter + quitar titutlo se pone solo con el nombre del articulo

2020-10-12 14:42 UTC, AlonsoOropeza requested changes
La información parece mejor en este nuevo commit, pero hace falta revisar la ortografía en el doc.

2020-10-14 14:38 UTC, Yaf98 commented
Hay un conflicto en el sidebar

2020-10-14 14:41 UTC, peterglezroa commented
Listo

2020-10-16 14:02 UTC, closed without merging