Guía de Creación de Métricas
novaDepto/Nova pull request #236
Opened 2020-11-27 03:27 UTC by A1365099

Sustituye a la 'Guía de Identificación de Métricas', agregando el modelo GQM(Goal-Question-Metric) que servirá para el PIP: Proceso de gestión de métricas

2020-11-27 03:47 UTC, ErwinAndresJL approved these changes
muy buena guía, me gusta el hecho que explican el método de Goal Question Metric. esta guía nos ayuda a no generar métricas por generarlas

2020-11-27 09:04 UTC, DanElias requested changes
Muy bien, solo creo que falta agregarlo a la sidebar. Si se modificó la matriz de configuración del departamento?

2020-11-27 18:29 UTC, A1365099 commented
Agregado a sidebar y a la matriz de configuración

2020-11-28 18:08 UTC, cmnb32 approved these changes

2020-11-28 21:59 UTC, DanElias approved these changes

2020-11-28 21:59 UTC, merged