Update and rename Guía-del-product-owner.md to Guía-del-Product-Owner.md
novaDepto/Nova pull request #254
Opened 2020-11-29 16:19 UTC by Raylogic

Este Pull Request es uno de varios para mover el contenido la Política de Roles y Responsabilidades a las guías de los roles y poder despreciarlo puesto que se encuentra repetida en ambos artefactos. Este Pull Request es para actualizar la Guía del Product Owner.

2020-11-29 16:25 UTC, ErwinAndresJL approved these changes
cuidado con el cambio de nombre, se rompió pudo haber roto el link en la sidebar / donde se hace referencia.

2020-11-29 17:07 UTC, DanElias requested changes
Si, falta cambiar sidebar

2020-11-29 19:14 UTC, irvingpercam approved these changes

2020-11-29 19:55 UTC, DanElias requested changes
@Raylogic e @irvingpercam NO ME HACEN CASO. Dije que no está la sidebar y no lo cambian. ¿Qué parte no se comprende? Por qué dice que está si no está. Me molesta que me hagan perder el tiempo volviendo a revisar cosas cuando NO ESTÁ HECHO EL CAMBIO.

2020-11-29 20:02 UTC, Raylogic commented
> @Raylogic e @irvingpercam NO ME HACEN CASO. Dije que no está la sidebar y no lo cambian. ¿Qué parte no se comprende? Por qué dice que está si no está. Me molesta que me hagan perder el tiempo volviendo a revisar cosas cuando NO ESTÁ HECHO EL CAMBIO. O si está cambiado en otro pull díganme donde y pongan el link.

El cambio se hizo en otro Pull Request.

2020-11-29 20:03 UTC, DanElias commented
> > @Raylogic e @irvingpercam NO ME HACEN CASO. Dije que no está la sidebar y no lo cambian. ¿Qué parte no se comprende? Por qué dice que está si no está. Me molesta que me hagan perder el tiempo volviendo a revisar cosas cuando NO ESTÁ HECHO EL CAMBIO. O si está cambiado en otro pull díganme donde y pongan el link.
> 
> El cambio se hizo en otro Pull Request.

en cual

2020-11-29 20:11 UTC, Raylogic commented
> > > @Raylogic e @irvingpercam NO ME HACEN CASO. Dije que no está la sidebar y no lo cambian. ¿Qué parte no se comprende? Por qué dice que está si no está. Me molesta que me hagan perder el tiempo volviendo a revisar cosas cuando NO ESTÁ HECHO EL CAMBIO. O si está cambiado en otro pull díganme donde y pongan el link.
> > 
> > 
> > El cambio se hizo en otro Pull Request.
> 
> en cual

Update_Sidebar.md, hace una hora

2020-11-29 20:12 UTC, Raylogic commented
> > > > @Raylogic e @irvingpercam NO ME HACEN CASO. Dije que no está la sidebar y no lo cambian. ¿Qué parte no se comprende? Por qué dice que está si no está. Me molesta que me hagan perder el tiempo volviendo a revisar cosas cuando NO ESTÁ HECHO EL CAMBIO. O si está cambiado en otro pull díganme donde y pongan el link.
> > > 
> > > 
> > > El cambio se hizo en otro Pull Request.
> > 
> > 
> > en cual
> 
> Update_Sidebar.md, hace una hora
 Incluso en el Pull Request: Actualizar Sidebar con links de guías de roles

2020-11-29 20:56 UTC, DanElias commented
> > > > @Raylogic e @irvingpercam NO ME HACEN CASO. Dije que no está la sidebar y no lo cambian. ¿Qué parte no se comprende? Por qué dice que está si no está. Me molesta que me hagan perder el tiempo volviendo a revisar cosas cuando NO ESTÁ HECHO EL CAMBIO. O si está cambiado en otro pull díganme donde y pongan el link.
> > > 
> > > 
> > > El cambio se hizo en otro Pull Request.
> > 
> > 
> > en cual
> 
> Update_Sidebar.md, hace una hora

Ese no se mergeo, y hay otro que dice update sidebar pero dice: * [\[GUI22\] Guía del Product Owner](https://github.com/novaDepto/Nova/wiki/Guía-del-product-owner) y debería ser Guía-del-Product-Owner

2020-11-30 00:01 UTC, Raylogic commented
> > > > > @Raylogic e @irvingpercam NO ME HACEN CASO. Dije que no está la sidebar y no lo cambian. ¿Qué parte no se comprende? Por qué dice que está si no está. Me molesta que me hagan perder el tiempo volviendo a revisar cosas cuando NO ESTÁ HECHO EL CAMBIO. O si está cambiado en otro pull díganme donde y pongan el link.
> > > > 
> > > > 
> > > > El cambio se hizo en otro Pull Request.
> > > 
> > > 
> > > en cual
> > 
> > 
> > Update_Sidebar.md, hace una hora
> 
> Ese no se mergeo, y hay otro que dice update sidebar pero dice: * [[GUI22] Guía del Product Owner](https://github.com/novaDepto/Nova/wiki/Gu%C3%ADa-del-product-owner) y debería ser Guía-del-Product-Owner

Ya para este punto ya me rendí con aceptar este Pull Request. SI el fix que acabo de subir no arregla esto, le pediré a otro Reviewer que lo pruebe.

2020-11-30 00:11 UTC, DanElias approved these changes

2020-11-30 00:11 UTC, merged