Deteccion de necesidades/acuerdo con socio
novaDepto/Nova pull request #255
Opened 2020-11-29 16:37 UTC by A01700043

2020-11-29 16:50 UTC, ErwinAndresJL approved these changes
Bien, en la parte de resonsables le quitaste el doble gato (##) y actualiza la versión a esta modificación que le hiciste. solo agrégalo .1

2020-11-29 18:43 UTC, ErwinAndresJL requested changes
.

2020-11-30 00:18 UTC, ErwinAndresJL approved these changes

2020-11-30 02:47 UTC, luisescobar8 approved these changes

2020-11-30 02:49 UTC, merged