Guia de especificaciond de requisitos en proceso
novaDepto/Nova pull request #258
Opened 2020-11-29 17:58 UTC by A01700043

2020-11-29 18:03 UTC, DanElias requested changes
Quedó mal el link, no se ve bien: necesita ser -> https://github.com/novaDepto/Nova/wiki/Guia-de%20-especificacion-requisitos

2020-11-29 18:04 UTC, ErwinAndresJL requested changes
El link de la entrada hace falta ponerlo de manera correcta, agregar el link en la parte de especificación y actualizar la versión

2020-11-29 23:44 UTC, ErwinAndresJL approved these changes

2020-11-30 02:44 UTC, luisescobar8 approved these changes

2020-11-30 20:47 UTC, closed without merging