Proceso de Asignación de Roles subido y corregido
novaDepto/Nova pull request #27
Opened 2020-10-05 17:44 UTC by Raylogic

Aquí está el Proceso de Asignación de Roles corregido.

2020-10-07 19:22 UTC, peterglezroa approved these changes

2020-10-09 14:54 UTC, peterglezroa requested changes
No se te olvide poner el link, después

2020-10-09 14:54 UTC, peterglezroa commented on Proceso-de-asignación-de-roles.md
Si es una guía, entonces es opcional completarla. Si quieres que se cumplan esos estándares mejor redacta una política alrededor de eso. En mi opinión quedaría mejor si mejor pones que se **_apoyen_** en la guía.

2020-10-11 17:36 UTC, peterglezroa approved these changes
:+1:

2020-10-12 03:39 UTC, DanElias reviewed
@Raylogic  Aquí yo sigo teniendo duda de las secciones de Políticas-Estándares y de Postrrequisitos. No las tenemos en los procesos que han hecho los demás y creo que ocurre lo mismo que nos comentó lalo de que era overhead tener una sección de prerrequisitos cuando ya se podía tener esa información en la sección de entradas. Yo recomendaría primero revisar con lalo si está bien tener las secciones de Políticas-Estándares y de Postrrequisitos por cualquier cosa

2020-10-12 03:41 UTC, DanElias reviewed
@Raylogic En la tabla de procesos tampoco debe de ir la columna de paso, lalo nos comentó que con la columna de Fase era suficiente

2020-10-12 14:44 UTC, AlonsoOropeza approved these changes
Excelente trabajo, conciso, buena ortografía y veo que ya se removió la parte de prerequisitos.
Sugiero que en métricas se sea más específico en cómo se mide esa motivación y tal vez eliminar la sección de postrequisitos e integrarla mejor en el proceso.

2020-10-12 23:48 UTC, merged