Proceso de Identificación de Riesgos subido y corregido
novaDepto/Nova pull request #28
Opened 2020-10-05 17:46 UTC by Raylogic

Aquí está el Proceso de Identificación de Riesgos corregido

2020-10-07 19:23 UTC, peterglezroa requested changes
Necesita validación de la área de cmmi encargada de riesgos

2020-10-12 03:46 UTC, DanElias commented on Proceso-de-identificación-de-riesgos.md
> +      <th>Fase</th>
La columna de Fase tiene los números de los pasos en vez de las fases. Igualmente, como nos comentó Lalo la columna de Pasos no debe de estar.

2020-10-12 14:46 UTC, AlonsoOropeza approved these changes
De nuevo muy buen trabajo, pero inisto en que el proceso siga la estrucutra entrada-->proceso-->salida. Sin pre/postrequisitos, mejor todo integrarlo. Para más detalle en caso requerido sugiero una guía.

2020-10-14 14:19 UTC, peterglezroa approved these changes

2020-10-14 14:19 UTC, merged