Proceso de Seguimiento de Riesgos subido y corregido
novaDepto/Nova pull request #29
Opened 2020-10-05 17:48 UTC by Raylogic

Aquí está el Proceso de Seguimiento de Riesgos corregido.

2020-10-07 19:24 UTC, peterglezroa requested changes
Necesita validación de la área de riesgos

2020-10-09 14:59 UTC, peterglezroa requested changes
Sólo hay que mantener un formato. También no lo voy a validar hasta que haya validación de un encargado de riesgos (si no todavía no hay, ni modo, hasta que haya un responsable de área)

2020-10-09 14:59 UTC, peterglezroa commented on Proceso-de-seguimiento-de-riesgos.md
> +## Precondiciones
Mejor cambialo a `## Entradas` para que se mantenga el formato en todos los archivos. Es uno de los puntos que nos señalaron en el SCAMPI

2020-10-11 17:34 UTC, peterglezroa requested changes
Lo veo bien. Sólo necesito que ya alguien de Riesgos lo haya revisado.

2020-10-12 02:40 UTC, Yaf98 commented on Proceso-de-seguimiento-de-riesgos.md
> +      <th>Paso</th>
Las columnas de paso y fase están invertidas

2020-10-12 02:40 UTC, Yaf98 commented on Proceso-de-seguimiento-de-riesgos.md
> +
Cambiaría "seguimiento" por "monitoreo" en el título

2020-10-12 02:40 UTC, Yaf98 commented on Proceso-de-seguimiento-de-riesgos.md
> +## Postrequisitos
Yo quitaría esto, al final de cuentas para eso están las salidas

2020-10-12 03:20 UTC, peterglezroa commented on Proceso-de-seguimiento-de-riesgos.md
> +
Anoma, yo ni me di cuenta jeje. Confirmo

2020-10-12 03:50 UTC, DanElias commented on Proceso-de-seguimiento-de-riesgos.md
> +      <th>Paso</th>
Y la de paso no debe de ir, eso nos dijo Lalo en la retro del SCAMPI

2020-10-12 03:52 UTC, DanElias commented on Proceso-de-seguimiento-de-riesgos.md
> +
@Raylogic x2 Justo iba a decir que me causaba ruido que hubiera un proceso de identificación de riesgos y uno de seguimiento. sentía que los dos se podían poner en uno solo. Pero concuerdo con Yaf, si esto está más relacionado con el monitoreo, sí cambiaría el título a Proceso de Monitoreo de Riesgos. Igualmente esto se lo debes de compartir a PMC @ErwinAndresJL y @AlexisVM que tienen como parte de esa área el Monitoreo de Riesgos

2020-10-12 14:48 UTC, AlonsoOropeza approved these changes
Siendo puntual en la review revisa lo que comentaron Dan, Peter y Yaf. De nuevo mejor simplificar y quitar los pre/post requisitos. Y estoy de acuerdo en que sea monitoreo mejor.

2020-10-12 23:49 UTC, peterglezroa commented on Proceso-de-seguimiento-de-riesgos.md
> +
Yo diría que se necesita la validación de uno de PMC

2020-10-14 14:20 UTC, peterglezroa approved these changes

2020-10-14 14:23 UTC, peterglezroa requested changes
Cambiar de proceso de seguimiento, proceso de monitoreo

2020-10-14 14:26 UTC, peterglezroa approved these changes

2020-10-14 14:26 UTC, merged