Guia para identificar procesos, guias y politicas
novaDepto/Nova pull request #31
Opened 2020-10-08 03:20 UTC by luisescobar8

2020-10-08 14:01 UTC, peterglezroa requested changes

2020-10-08 14:01 UTC, petergroa commented on Guía para identificar procesos, guías y_o políticas.md
> +## Determinación
Y esto? Está incompleto?

2020-10-08 14:01 UTC, peterglezroa commented on Guía para identificar procesos, guías y_o políticas.md
> +### Proceso
Yo pondría que también es algo que es **imperativo** ejecutar en nuestra forma de trabajo

2020-10-09 19:23 UTC, marlagr commented
Yo agregaría las ligas a los templates de guías, procesos.

2020-10-09 20:19 UTC, AlonsoOropeza approved these changes

2020-10-09 20:21 UTC, AlonsoOropeza approved these changes

2020-10-09 20:26 UTC, irvingpercam approved these changes
Revisado.

2020-10-09 20:31 UTC, luisescobar8 commented on Guía para identificar procesos, guías y_o políticas.md
> +### Proceso
Ya corregí con otros compañeros jeje

2020-10-11 17:29 UTC, peterglezroa approved these changes
:+1: súper

2020-10-11 17:29 UTC, merged