Proceso para definir un proceso - quitar los pasos
novaDepto/Nova pull request #33
Opened 2020-10-08 18:29 UTC by peterglezroa

2020-10-09 12:18 UTC, ErwinAndresJL approved these changes
Excelente Pedro, vi que quitaste los pasos de acuerdo a la retro que recibimos de no ordenar cada uno. El proceso ya estaba bien.

2020-10-09 19:29 UTC, DanElias commented
Muy bien

2020-10-09 19:31 UTC, DanElias requested changes
Como nos mencionó lalo en la retro, falta también quitar los prerrequisitos y dejar solo la sección de entradas

2020-10-11 17:32 UTC, peterglezroa commented
Listo :+1: @DanElias

2020-10-12 02:44 UTC, Yaf98 commented on Proceso-para-definir-un-proceso.md
>        <td>Identificar los prerequisitos.</td>
Si se quitan los prerequisitos del formato , entonces también se quitarían aquí no?

2020-10-12 02:44 UTC, Yaf98 commented on Proceso-para-definir-un-proceso.md
>          Corroborar que el proceso tiene mínimo:
Creo que aquí también sería quitar "Prerequisitos"

2020-10-12 03:22 UTC, peterglezroa commented on Proceso-para-definir-un-proceso.md
>          Corroborar que el proceso tiene mínimo:
Pero ya los quité :cry:. Chance estás viendo lo que quité (tiene una franja roja en la izq si lo visualizas como documento)

2020-10-12 03:56 UTC, DanElias commented on Proceso-para-definir-un-proceso.md
>          Corroborar que el proceso tiene mínimo:
@peterglezroa a mi me sale que ya quitaste la sección de prerrequisitos pero me sigue saliendo la columna de pasos que según yo ya habías quitado. Nose si me sale mal el commit o algo, pero dice que fue el último

2020-10-12 03:59 UTC, DanElias commented on Proceso-para-definir-un-proceso.md
>          Corroborar que el proceso tiene mínimo:
se cancela ya vi como ver la última versión del documento. Ya lo voy a aprobar :)

2020-10-12 04:00 UTC, DanElias approved these changes

2020-10-12 04:05 UTC, DanElias commented on Proceso-para-definir-un-proceso.md
>          Corroborar que el proceso tiene mínimo:
Pero regresando al comentario de Yaf, sí, en la tabla en las fases aún sale identificar los "prerequisitos" y pues ya no aplica :0

2020-10-12 12:59 UTC, peterglezroa commented on Proceso-para-definir-un-proceso.md
>          Corroborar que el proceso tiene mínimo:
Ah ya lo vi. Vava, lo cambio

2020-10-12 14:51 UTC, AlonsoOropeza approved these changes
Me parece bien simplificar a que sólo sea entrada->proceso->salida. Justamente si se requiere más detalle para eso están las guías. Excelente trabajo, según yo con esto se quitan lo de pre/post requisitos no?

2020-10-12 15:24 UTC, luisescobar8 approved these changes

2020-10-12 15:30 UTC, luisescobar8 commented on Proceso-para-definir-un-proceso.md
>        <th>Fase</th>
La numeración según la revisión de hockey, va en las fases jeje

2020-10-12 20:14 UTC, merged