Proceso para Institucionalizar - agregar link en sidebar
novaDepto/Nova pull request #34
Opened 2020-10-08 19:25 UTC by peterglezroa

Proceso para facilitar institucionalizar los documentos

2020-10-09 19:42 UTC, DanElias requested changes
Como nos comentó Lalo, en los procesos se debe de tener la tabla que se definió en el proceso para definir procesos, ya sin el la columna de pasos. Igualmente, falta quitar la sección de prerrequisitos y dejar eso en una sola sección de entradas. :)

2020-10-11 17:26 UTC, peterglezroa commented
> Igualmente, falta quitar la sección de prerrequisitos y dejar eso en una sola sección de entradas. :)
Ya hice los cambios :)

> Como nos comentó Lalo, en los procesos se debe de tener la tabla que se definió en el proceso para definir procesos, ya sin el la columna de pasos. 
No entiendo esta parte. En uno de los commits anteriores quité la lista  y la convertí en una tabla parecida a la que hice en el proceso para definir procesos. Me falta algo?

2020-10-12 02:46 UTC, Yaf98 approved these changes

2020-10-12 04:07 UTC, DanElias commented
@peterglezroa Si ya vi que ya quedó, jeje quizá vi una versión viejita. Ya lo aprobaré :)

2020-10-12 04:07 UTC, DanElias approved these changes

2020-10-12 04:07 UTC, merged