Update Proceso-de-gestion-de-metricas.md
novaDepto/Nova pull request #35
Opened 2020-10-09 19:50 UTC by Raylogic

2020-10-09 20:10 UTC, DanElias requested changes
No entiendo bien la sección de Políticas o estándares, pero de ser necesaria, primero habría que agregar esta sección al proceso para definir proceso como una sección opcional. O quizá no como una sección, sino incluir esa parte en los pasos del proceso como hipervínculos a las política o estándar en el cual se deben de basar. Igualmente recuerda quitar los pasos de la tabla de los pasos, y solo dejar las fases. Así mismo, lo que viene en la sección de post requisitos lo pondría junto con las salidas más que nada porque recuerda que lalo nos dijo que quitáramos la de prerrequisitos y los pusiéramos junto con las entradas, supongo que es el mismo caso pero con salidas y postrequisitos.

2020-10-11 17:19 UTC, peterglezroa commented on Proceso-de-gestion-de-metricas.md
> +1. Los datos antiguos deben guardarse como histórico.
Más que Postrequisitos yo lo pondría como una salida. Cómo `documento histórico de los datos`.

2020-10-11 17:21 UTC, peterglezroa approved these changes

2020-10-12 04:11 UTC, DanElias reviewed
@Raylogic A mi me sigue saliendo la columna de pasos que lalo nos comentó que quitáramos

2020-10-12 04:46 UTC, manu-yaff commented on Proceso-de-gestion-de-metricas.md
>  1. Asegurar la recogida, análisis y comunicación de las métricas
¿Cuál es la importancia de hacer esto?

2020-10-12 14:52 UTC, AlonsoOropeza commented on Proceso-de-gestion-de-metricas.md
> +      <td>Recogida</td>
Mejor recolección por obvias razones

2020-10-12 14:54 UTC, AlonsoOropeza approved these changes
Mira me parece bien pero te voy a pedir dos cambios, lo que dice Yaf sobre que hagas ver la importancia del doc y cambia el título del doc para que sea "Proceso de gestión de métricas", y no nos digan nada de ortografía.

2020-10-14 14:29 UTC, DanElias commented
@Raylogic Creo que la parte de comunicar las métricas, se le comunica más a PMC que a PPQA. O puede ser a los dos, PPQA solo revisa que se esté llenando el defect log y otras métricas de calidad, pero PMC es el que muestra ya el monitoreo.

2020-10-14 15:01 UTC, AlejandroMinaya approved these changes

2020-10-16 02:32 UTC, Yaf98 commented on Proceso-de-gestión-de-métricas.md
> +## Objetivo (SMARTish)
Hay que quitar el "(SMARTish)"

2020-10-16 03:48 UTC, ErwinAndresJL commented on Proceso-de-gestión-de-métricas.md
> +## Objetivo (SMARTish)
Yo tampoco entiendo por qué varios tienens SMARTish

2020-10-16 03:50 UTC, ErwinAndresJL approved these changes

2020-10-16 04:07 UTC, ErwinAndresJL requested changes

2020-10-16 04:07 UTC, ErwinAndresJL commented on Proceso-de-gestión-de-métricas.md
> +3. Disponibilizar las métricas para el departamento.
Tengo entendido que según la RAE, es mejor: "Poner a disposición" que "Disponibilizar"

2020-10-16 14:09 UTC, ErwinAndresJL approved these changes

2020-10-16 15:03 UTC, AlejandroMinaya approved these changes

2020-10-16 15:05 UTC, AlejandroMinaya commented
@Raylogic sólo faltan los cambios de @DanElias para que se apruebe.

2020-10-16 15:43 UTC, Raylogic commented
Jovenazo, lo de Dan ya fue corregido, el tema es que como es un comentario y no una corrección, no puedo hacer "Resolve Conversation"

2020-10-16 15:56 UTC, DanElias approved these changes

2020-10-16 15:56 UTC, merged