Política de Gestión de Métricas
novaDepto/Nova pull request #37
Opened 2020-10-09 20:00 UTC by Raylogic

2020-10-11 17:17 UTC, peterglezroa approved these changes

2020-10-12 02:55 UTC, Yaf98 commented on Política-de-gestión-de-métricas.md
> +2. Las métricas se recogen, analizan y comunican por quincena para ver el progreso general del equipo y departamento
¿Cómo se ve ese progreso?¿A quién le toca mostrar este progeso?

2020-10-12 02:55 UTC, Yaf98 commented on Política-de-gestión-de-métricas.md
> +3. Se espera que el departamento documente la información de su trabajo para asegurar la efectividad de las métricas. Queda a cargo de las demás áreas actualizar sus propios datos.
- ¿Cuáles áreas?¿CMMI?

- ¿Cómo se documenta la información?¿Cómo aseguro la efectividad de las métricas?

2020-10-12 02:55 UTC, Yaf98 commented on Política-de-gestión-de-métricas.md
> +4. Queda prohibido truncar los datos de las tablas que alimentan a las métricas
No entendí cuales tablas

2020-10-12 02:55 UTC, Yaf98 commented on Política-de-gestión-de-métricas.md
> +1. Asegurar la efectividad y transparencia en el manejo de las métricas del departamento
¿Para que quiere el departamento la efectividad y transparencia en las métricas?

2020-10-12 04:13 UTC, DanElias commented on Política-de-gestión-de-métricas.md
> +2. Las métricas se recogen, analizan y comunican por quincena para ver el progreso general del equipo y departamento
Concuerdo con que se debe de incluir lo que menciona Yaf

2020-10-12 04:16 UTC, DanElias commented on Política-de-gestión-de-métricas.md
> +3. Se espera que el departamento documente la información de su trabajo para asegurar la efectividad de las métricas. Queda a cargo de las demás áreas actualizar sus propios datos.
Añadiendo a lo de Yaf, yo también especificaría puntualmente o en bullet points cuáles son las métricas o ejemplos de métricas que se deben de recopilar por el depto. y los equipos y a qué áreas del CMMI están midiendo. También. ¿Cómo es que se comunican las métricas, dónde se deben de poner?

2020-10-12 04:17 UTC, DanElias commented on Política-de-gestión-de-métricas.md
> +4. Queda prohibido truncar los datos de las tablas que alimentan a las métricas
Si, falta poner en específico qué tablas o mejor mencionar que en general, cualquier métrica que esté en cualquier documento/repositorio/sitio/aplicación del depto. no debe de ser manipulada para mostrar datos falsos.

2020-10-12 04:18 UTC, DanElias commented on Política-de-gestión-de-métricas.md
> +1. Asegurar la efectividad y transparencia en el manejo de las métricas del departamento
Así es, el objetivo debería de estar dando la solución a una necesidad del depto.

2020-10-12 04:20 UTC, DanElias commented on Política-de-gestión-de-métricas.md
> +3. Se espera que el departamento documente la información de su trabajo para asegurar la efectividad de las métricas. Queda a cargo de las demás áreas actualizar sus propios datos.
Más que nada, como es una política, definir estas métricas para que sea **obligatorio** que el depto y los equipos tengan estas métricas.

2020-10-12 04:24 UTC, DanElias commented on Política-de-gestión-de-métricas.md
> +3. Se espera que el departamento documente la información de su trabajo para asegurar la efectividad de las métricas. Queda a cargo de las demás áreas actualizar sus propios datos.
+ test coverage: porcentaje de líneas/branches/clases en el código que fueron cubiertas por las pruebas.

2020-10-12 14:46 UTC, luisescobar8 commented on Política-de-gestión-de-métricas.md
> +2. Las métricas se recogen, analizan y comunican por quincena para ver el progreso del equipo
También creo que las métricas deben de ser recogidas y analizadas y comunicadas cada semana ya que el reporte de estado es cada semana.

2020-10-12 14:56 UTC, AlonsoOropeza requested changes
Checa la review de Dan y Yaf, de mi parte como librarian está bien el formato/estructura/ortografía.

2020-10-15 14:45 UTC, peterglezroa approved these changes

2020-10-16 03:40 UTC, ErwinAndresJL requested changes

2020-10-16 03:40 UTC, ErwinAndresJL commented on Política-de-gestión-de-métricas.md
> +Departamento > Desarrollo del Departamento > CMMI > MA > Backlog de Métricas.
Hoy se incorporó el directorio de archivos a la wiki, cambiar el path de drive a solo indicar que lo encuentran en el directorio en el área de MA. Yo ya los pude consultar desde ahí y está más fácil encontrarlo.

2020-10-16 14:08 UTC, ErwinAndresJL approved these changes

2020-10-16 14:57 UTC, AlonsoOropeza approved these changes
Me agrada lo de la transparencia, hay cosas que todavía me hacen ruido pero poniéndolo en la práctica seugramente se resuelven.

2020-10-16 15:02 UTC, merged