Se corrigió el enlace al repositorio usado por Andrómeda
novaDepto/Nova pull request #48
Opened 2020-10-14 15:30 UTC by cmnb32

2020-10-14 15:51 UTC, peterglezroa requested changes

2020-10-14 15:51 UTC, peterglezroa commented on Home.md
> +[Canis Maioris](https://github.com/novaDepto/PugSeal)
Hay un typo

2020-10-15 14:43 UTC, peterglezroa approved these changes
:heart:

2020-10-16 03:23 UTC, ErwinAndresJL requested changes

2020-10-16 03:23 UTC, ErwinAndresJL commented on Home.md
> +[Canis Majoris](https://github.com/novaDepto/PugSeal)
Creo que el nombre del equipo es con doble n, salu2

2020-10-16 14:25 UTC, peterglezroa commented on Home.md
> +[Canis Majoris](https://github.com/novaDepto/PugSeal)
F

2020-10-16 14:52 UTC, cmnb32 commented on Home.md
> +[Canis Majoris](https://github.com/novaDepto/PugSeal)
Cambiado

2020-10-17 04:26 UTC, DanElias approved these changes
Niceu

2020-10-18 21:51 UTC, Yaf98 approved these changes

2020-10-19 15:44 UTC, peterglezroa commented
@ErwinAndresJL Necesitamos que lo revises jeje

2020-10-20 17:36 UTC, ErwinAndresJL approved these changes

2020-10-20 17:36 UTC, merged