Arreglar link roto de Política de Juntas
novaDepto/Nova pull request #50
Opened 2020-10-15 02:58 UTC by DanElias

Arreglar link roto de Política de Juntas

2020-10-15 02:58 UTC, marlagr approved these changes

2020-10-15 14:42 UTC, peterglezroa requested changes

2020-10-15 14:42 UTC, peterglezroa commented on _Sidebar.md
> -* [\[PRO05\] Proceso para auditorías](https://github.com/novaDepto/Nova/wiki/Proceso-de-auditorías)
Quitaste la línea por accidente?

2020-10-15 16:47 UTC, DanElias commented on _Sidebar.md
> -* [\[PRO05\] Proceso para auditorías](https://github.com/novaDepto/Nova/wiki/Proceso-de-auditorías)
Nope, estaba repetido. El proceso de auditorías ya está en el PRO02.

2020-10-16 03:28 UTC, ErwinAndresJL approved these changes

2020-10-16 03:58 UTC, Yaf98 commented on _Sidebar.md
> +* [\[POL04\] Política-de-Juntas](https://github.com/novaDepto/Nova/blob/master/Pol%C3%ADtica-de-Juntas.md)
@DanElias hay que quitar el .md. Creo que el link correcto es: https://github.com/novaDepto/Nova/wiki/Pol%C3%ADtica-de-Juntas

2020-10-16 04:05 UTC, DanElias commented on _Sidebar.md
> +* [\[POL04\] Política-de-Juntas](https://github.com/novaDepto/Nova/blob/master/Pol%C3%ADtica-de-Juntas.md)
según yo da igual pero deja lo quito

2020-10-16 04:07 UTC, DanElias commented on _Sidebar.md
> +* [\[POL04\] Política-de-Juntas](https://github.com/novaDepto/Nova/blob/master/Pol%C3%ADtica-de-Juntas.md)
@Yaf98 ya

2020-10-16 04:31 UTC, Yaf98 approved these changes

2020-10-16 14:25 UTC, peterglezroa commented on _Sidebar.md
> -* [\[PRO05\] Proceso para auditorías](https://github.com/novaDepto/Nova/wiki/Proceso-de-auditorías)
Ah ya

2020-10-16 14:26 UTC, peterglezroa approved these changes

2020-10-16 14:26 UTC, merged