Guía de uso de Clockify
novaDepto/Nova pull request #51
Opened 2020-10-15 03:12 UTC by A1365099

Mejorar el monitoreo de tiempo de las actividades.

Documento con los pasos para utilizar Clockify.

2020-10-15 03:29 UTC, DanElias commented
Está muy bien. Solo creo que a nivel departamento falta que se definan tags para poder filtrar los tiempos, definir lo que se considera billable ($), y cómo hacerle para que todos pongan siempre el mismo nombre a la tarea que se está realizando en parejas o equipo.

2020-10-15 14:40 UTC, peterglezroa requested changes

2020-10-15 14:40 UTC, peterglezroa commented on Guía de uso de Clockify.md
> +<br>
Yo digo que aquí se especifíque que **tome el nombre exacto que se despliega en el plan**. Esto es porque no hay un estándar y está imposible sacar reportes

2020-10-16 02:41 UTC, marlagr commented on Guía de uso de Clockify.md
> +
Aquí hay que subirlo sin titulo por que sino se duplica en la wiki.

2020-10-16 03:13 UTC, ErwinAndresJL commented on Guía de uso de Clockify.md
> +Mejorar el monitoreo de tiempo de las actividades a través de:
Siento que el objetivo tiene que ser el objetivo de la guía, no del por qué se usará clockify, por ejemplo:
Objetivo: Orientar a los miembros del departamento a hacer un correcto registro en clockify.

Así queda claro para qué es esta guía, el objetivo de usar clockify podría ir en la introducción aunque trataría de que la intro fuera lo más corta y concisa posible para que el documento tome mucho tiempo a los miembros del departamento.

2020-10-16 03:13 UTC, ErwinAndresJL commented on Guía de uso de Clockify.md
> +
Aquí antes de empezar a medir el tiempo, falta el agregar el uso de tags, dejar claro para qué se usa cada uno ya que sirve al momento de hacer reportes.

También como menciona Dan, dejar claro cuándo es Billable ($) que por lo que tengo entendido es cuando se realizan aactividades que estaban planeadas, pero hay que especificarlo

2020-10-17 04:24 UTC, DanElias approved these changes
Nice! A mi me parece que ya está bien.

2020-10-18 02:40 UTC, marlagr approved these changes

2020-10-19 15:47 UTC, peterglezroa approved these changes

2020-10-19 15:47 UTC, merged