Add Procesos para planear iteraciones
novaDepto/Nova pull request #55
Opened 2020-10-16 14:35 UTC by cmnb32

2020-10-16 14:57 UTC, AlejandroMinaya requested changes

2020-10-16 14:57 UTC, AlejandroMinaya commented on Proceso-para-Planificar-Iteracion.md
> +
¿En este caso de obviaron las métricas para evaluar el proceso adrede ó hacen falta?

2020-10-18 02:38 UTC, marlagr commented on Proceso-para-Planificar-Iteracion.md
> +      <td >Análisis</td>
En la entrada o en la fase de análisis, yo agregaría "Adoptar una agenda de demostraciones con stakeholders:
- Demostración de la Iteración
- Demostración bajo demanda
- All hands demostration "

2020-10-20 18:03 UTC, ErwinAndresJL approved these changes

2020-10-22 17:44 UTC, marlagr approved these changes

2020-10-22 18:05 UTC, marlagr commented
@AlejandroMinaya

2020-10-23 14:35 UTC, AlejandroMinaya approved these changes

2020-10-23 14:43 UTC, merged