Actualización proceso planificación
novaDepto/Nova pull request #57
Opened 2020-10-16 14:53 UTC by AlonsoOropeza

Que tal actualizamos este proceso para que cumpla la plantilla y el proceso de procesos.

2020-10-16 15:01 UTC, AlejandroMinaya commented
Siento que aquí puede sobrelaparse este proceso y el proceso que está creando
@cmnb32

2020-10-16 15:05 UTC, cmnb32 reviewed
En general me parece bien el cambio, sin embargo creo que hace falta hacer referencia a otras guias/procesos/políticas que puedan ayudar.

2020-10-16 15:06 UTC, AlonsoOropeza commented
@ cmnb32 Justo Marla me dijo lo mismo ya lo anexé.

2020-10-16 15:07 UTC, AlonsoOropeza commented
> Siento que aquí puede sobrelaparse este proceso y el proceso que está creando
> @cmnb32

A que te refieres Juan ?
para corregirlo

2020-10-16 15:08 UTC, AlejandroMinaya requested changes

2020-10-16 15:08 UTC, AlejandroMinaya commented on Proceso-para-Planificar.md
> +## Importancia
Esta parte de importancia no es parte de la plantilla del proceso. No sé si
esto cause ruido. De ser necesario, recomiendo modificar la plantilla del
proceso para que lo incluya.

2020-10-16 15:11 UTC, AlejandroMinaya commented
> > Siento que aquí puede sobrelaparse este proceso y el proceso que está creando
> > @cmnb32
> 
> A que te refieres Juan ?
> para corregirlo

En el proceso que ahorita está haciendo @cmnb32 (Proceso para planear la iteración) también habla de estimar el tamaño y asignar responsabilidades para las tareas. No sé si se puede tener este tipo de empalmes entre los procesos o si uno puede depender de otro tipo un subproceso. Ahorita no es un request de cambio, sino para saber que procede tradicionalmente.

2020-10-16 22:50 UTC, marlagr commented on Proceso-para-Planificar.md
> +Para complementar, te invitamos a revisar esta [guía.](https://github.com/novaDepto/Nova/wiki/Gu%C3%ADa-para-definir-un-WBS)
Me gusta 😬, aquí solo en vez de ponerlo como una sección aparte en guía, lo pondría en entrada o como soporte al punto 1 de entrada.

2020-10-16 22:50 UTC, marlagr commented on Proceso-para-Planificar.md
> +## Importancia
Aquí concuerdo con Juan, creo que es mejor retirar esta sección.

2020-10-16 22:53 UTC, marlagr commented on Proceso-para-Planificar.md
>  ## Entrada
Uffff!, La entrada me parece clara y concisa, lo cuál facilita la planeación, nos va a servir mucho 😬👍

2020-10-17 04:14 UTC, DanElias commented
@AlejandroMinaya Aquí creo que este es para planificar en general. En el mapa de procesos entraría como un proceso general que puede aplicarse para cualquier fase del desarrollo del depto. o de un proyecto. El de @cmnb32 es más específico para la fase de construcción y planear la iteración de fase de construcción. Entonces ese entraría en la sección de iteración en el mapa de procesos. Me corrigen si estoy mal

2020-10-20 17:52 UTC, ErwinAndresJL commented on Proceso-para-Planificar.md
> +Para complementar, te invitamos a revisar esta [guía.](https://github.com/novaDepto/Nova/wiki/Gu%C3%ADa-para-definir-un-WBS)
concuedo con marla, no pondría una sección de guía, si no que lo pondría como soporte de entrada. consultar la guía de wbs

2020-10-20 17:57 UTC, ErwinAndresJL requested changes

2020-10-20 17:57 UTC, ErwinAndresJL commented on Proceso-para-Planificar.md
> +        <td>PP</td>
Creo que también agregaría el obtener compromiso de los involucrados en el plan, es necesario que los que están en el plan entiendan y se comprometan en sus actividades y tiempo que deberán destinar.

2020-10-21 14:53 UTC, AlonsoOropeza commented on Proceso-para-Planificar.md
> +        <td>PP</td>
Pero si está incluido después.

2020-10-21 14:56 UTC, AlonsoOropeza commented
> En el proceso que ahorita está haciendo @cmnb32 (Proceso para planear la iteración) también habla de estimar el tamaño y asignar responsabilidades para las tareas. No sé si se puede tener este tipo de empalmes entre los procesos o si uno puede depender de otro tipo un subproceso. Ahorita no es un request de cambio, sino para saber que procede tradicionalmente.

Ya respondiendo a esto este proceso es más viejo y ataca principalmente a la planeación general es parte de PP también.

2020-10-21 17:49 UTC, marlagr approved these changes

2020-10-22 18:01 UTC, DanElias approved these changes

2020-10-22 18:04 UTC, marlagr commented
@AlejandroMinaya  @ErwinAndresJL

2020-10-22 19:17 UTC, ErwinAndresJL approved these changes

2020-10-22 19:21 UTC, AlejandroMinaya approved these changes
Amazing job! Keep it up guys!

2020-10-22 19:21 UTC, merged