proceso para gestionar una historia de usuario
novaDepto/Nova pull request #59
Opened 2020-10-16 16:14 UTC by luisescobar8

2020-10-16 22:38 UTC, marlagr commented on Proceso-para-gestionar-una-historia-usuario.md
> +      <td rowspan="3">Identificar Documentacion</td>
Aquí solo falta el acento en Documentación

2020-10-17 03:46 UTC, DanElias reviewed
Me parece que a este proceso le hace falta más contenido, creo que en este solo se llega hasta la parte de análisis y diseño y la validación final. Pero, qué hay de la construcción, pruebas y despliegue? Qué se hace después de validar el análisis y diseño? A menos que eso vaya en un proceso aparte, le cambiaría el nombre a Proceso para Gestionar el Análisis y Diseño de una historia de usuario ya que no incluye las demás fases 😬.

2020-10-17 03:56 UTC, DanElias commented on Proceso-para-gestionar-una-historia-usuario.md
> +      <td>Solicitar la evaluación por parte del Architecture Owner o Team Leader</td>
Otra cuestión que me hace ruido es que se valida por el AO. ¿Qué hay de la verificación? Creo que incluyéndome, me hace falta revisar más a fondo la diferencia entre verificación y validación. Pero creo que ambas se requieren. Por lo que he entendido la verificación la hace el AO y la validación el PO. Pero creo que sería bueno revisar en asesoría esas cuestiones, porque no lo tenemos muy claro. Es muy muy importante que definimos exactamente en que parte de nuestro proceso de gestión de historias de usuario hacemos validación y verificación.

2020-10-17 03:56 UTC, DanElias commented on Proceso-para-gestionar-una-historia-usuario.md
> +      <td>Solicitar la evaluación por parte del Architecture Owner o Team Leader</td>
Igualmente creo que el TL no debería de aparecer aquí

2020-10-17 04:01 UTC, DanElias requested changes

2020-10-17 04:01 UTC, DanElias commented on Proceso-para-gestionar-una-historia-usuario.md
> +      <td>Autor del proceso</td>
Otra nota es la columna de responsable. El autor de proceso es el encargado de todos los pasos? Creo que aquí lo cambiaría a que todos somos responsables poniendo que el encargado es un miembro del departamento o la persona(s) que realizarán el análisis y diseño de la historia de usuario. Si no se entiende que Luis o Cris serán los que van a organizar la estructura  de los documentos, llenar el monitoreo, etc... para todas las historias de usuario de todos los equipos de desarrollo de software.

2020-10-21 15:18 UTC, closed without merging