guia para analisis y diseno de historias
novaDepto/Nova pull request #60
Opened 2020-10-16 16:25 UTC by luisescobar8

2020-10-16 17:02 UTC, DanElias requested changes

2020-10-16 17:02 UTC, DanElias commented on Guia-para-analisis-y-diseno-de-historias-de-usuario.md
> +            7. Los <strong>criterios de aceptación</strong> son definidos por el responsable del análisis y el diseño de cada historia de usuario.</br></br><strong>Funcionalidad</strong></br>Pruebas
En pruebas de unidad en vez de Unity Test es Unit Testing/Tests. Sin la "y"

2020-10-16 17:02 UTC, DanElias commented on Guia-para-analisis-y-diseno-de-historias-de-usuario.md
> +            7. Los <strong>criterios de aceptación</strong> son definidos por el responsable del análisis y el diseño de cada historia de usuario.</br></br><strong>Funcionalidad</strong></br>Pruebas
También falta el "¿" en las pregunta: ¿Realiza lo que tiene que realizar?

2020-10-16 17:02 UTC, DanElias commented on Guia-para-analisis-y-diseno-de-historias-de-usuario.md
> +            7. Los <strong>criterios de aceptación</strong> son definidos por el responsable del análisis y el diseño de cada historia de usuario.</br></br><strong>Funcionalidad</strong></br>Pruebas
Igual quitaría lo de gestionar correctamente la memoria porque creo que los equipos no tienen muy claro como se hace eso. Igual lo de Comité de ética lo pondría como Revisión de el impacto ético de la solución o no solo poner Comité de ética porque no se entiende qué hacer.

2020-10-16 17:02 UTC, DanElias commented on Guia-para-analisis-y-diseno-de-historias-de-usuario.md
> +            7. Los <strong>criterios de aceptación</strong> son definidos por el responsable del análisis y el diseño de cada historia de usuario.</br></br><strong>Funcionalidad</strong></br>Pruebas
En "Que el socio satisfecho" creo que falta el "quede" -> " Que el socio quede satisfecho". Luego dice: "Que el socio firme de acuerdo?" (es pregunta o si se debe de hacer?, hay formato de acuerdo?) Y eso de las 3 oportunidades de cambio fue una idea pero creo que después quedó en que se debe de ir agregando a la work items list como baja prioridad, entonces lo quitaría.

2020-10-22 19:49 UTC, marlagr approved these changes

2020-10-23 17:04 UTC, marlagr commented on Guia-para-analisis-y-diseno-de-historias-de-usuario.md
> +                8. Generar el <strong>diagrama de actividad</strong> de ha historia de usuario.</br></br><strong>Nota: </strong>El diagrama de actividad describe el flujo de la historia de usuario, m
Typo en  Generar el dragram de actividad "de ha" historia de usuario

2020-10-25 22:51 UTC, closed without merging

2020-10-25 22:51 UTC, DanElias commented
Obsoleto