Guía de Identificación de Métricas
novaDepto/Nova pull request #64
Opened 2020-10-19 18:05 UTC by Raylogic

Aquí está el listado y descripción de las métricas actuales del departamento.

2020-10-20 03:01 UTC, DanElias reviewed
Bien, solo también agregaría lo de la encuesta de satisfacción del departamento que en realidad son otras 9 métricas sobre felicidad, motivación, etc. que se recogen cada semana solo a nivel departamental

2020-10-20 03:02 UTC, DanElias requested changes
@Raylogic También aquí falta agregar a la sidebar jeje

2020-10-22 01:16 UTC, marlagr approved these changes

2020-10-22 15:49 UTC, DanElias approved these changes

2020-10-22 15:49 UTC, merged