Update Proceso-de-gestión-de-métricas.md
novaDepto/Nova pull request #65
Opened 2020-10-19 18:33 UTC by Raylogic

2020-10-20 02:57 UTC, DanElias requested changes
Muy bien, pero creo que en la tablita de al principio **falta el Dueño del proceso** (esto lo vamos a ocupar para gestionar los cambios en CM). Igual en los objetivos pondría uno enfocado a una necesidad: Las métricas le permiten al departamento conocer su estado basado en datos concretos para así mejorar conforme pasa el tiempo (o algo así). Igual en la columna de encargado en vez de MA pondría miembro del área de MA. Pero lo importante es lo de poner el dueño del proceso para cumplir con CM

2020-10-20 02:58 UTC, DanElias commented
@Raylogic También falta agregarlo a la sidebar

2020-10-22 18:02 UTC, DanElias approved these changes

2020-10-22 18:05 UTC, marlagr approved these changes

2020-10-22 18:05 UTC, merged