Proceso de medidas correctivas
novaDepto/Nova pull request #69
Opened 2020-10-20 14:29 UTC by ErwinAndresJL

2020-10-20 15:56 UTC, DanElias requested changes
En la tablita de nombre/rol salen las rayas punteadas como celdas en la tabla. Igual falta poner el el rol de dueño del proceso porque se ocupa para CM. En el objetivo dice: "Para que alcanzar", creo que era para alcanzar. Los demás está muy bien :)

2020-10-21 17:21 UTC, ErwinAndresJL commented
Listo, se corrigió: La tabla inicial con las líneas punteadas, se puso el dueño del proceso, el error gramatical del objetivo y se puso el link al formato de gestión de medidas correctivas

2020-10-22 15:47 UTC, DanElias approved these changes

2020-10-22 17:52 UTC, marlagr approved these changes

2020-10-22 17:52 UTC, merged