update: Proceso de identificación de riesgos
novaDepto/Nova pull request #73
Opened 2020-10-20 15:37 UTC by ErwinAndresJL

Se actualizó el proceso de identificación de riesgos y se agregó a la sidebar

2020-10-20 15:52 UTC, DanElias requested changes
Solo falta poner el la tablita de autor, el que es va a ser el Dueño del Proceso. Eso se ocupa para CM :)

2020-10-21 18:13 UTC, ErwinAndresJL commented
Listo, se corrigió la tabla inicial, se puso link al lugar para encontrar las matrices de riesgo

2020-10-22 01:17 UTC, marlagr approved these changes

2020-10-22 17:58 UTC, DanElias approved these changes

2020-10-22 17:59 UTC, DanElias approved these changes

2020-10-22 17:59 UTC, merged