Add markdown cheat sheet
novaDepto/Nova pull request #8
Opened 2020-09-26 23:26 UTC by Yaf98

2020-09-27 21:40 UTC, peterglezroa commented on markdown-guide.md
> +## Ordered lists
Un comentario

2020-09-27 21:46 UTC, peterglezroa requested changes

2020-09-27 21:46 UTC, peterglezroa commented on markdown-guide.md
> +* Second item
No me gusta

2020-09-27 21:51 UTC, peterglezroa approved these changes
Muy bien Yaf :+1: :smile:

2020-09-28 17:49 UTC, AlonsoOropeza commented
Que es esto? Cómo una especie de guía de markdown?

2020-09-30 02:26 UTC, Yaf98 commented
> Que es esto? Cómo una especie de guía de markdown?
> Me agrada lo que tiene pero le falta titulo y saber en que sección pertenece guía, proceso, política por ejemplo
> "Guía para markdown o algo así"



> Que es esto? Cómo una especie de guía de markdown?
> Me agrada lo que tiene pero le falta titulo y saber en que sección pertenece guía, proceso, política por ejemplo
> "Guía para markdown o algo así"

Era sólo un ejemplo para que Peter hiciera una guía de como hacer reviews, pero si la quieren usar adelanta jaja

2020-10-02 14:34 UTC, closed without merging