add politica de habilidades
novaDepto/Nova pull request #88
Opened 2020-10-21 20:46 UTC by marlagr

- Desarrollar los conocimientos, confianza y habilidades entre los miembros del departamento, para lograr un equipo de alto desempeño.

2020-10-21 22:01 UTC, DanElias requested changes

2020-10-21 22:01 UTC, DanElias commented on Politica-de-gestion-habilidades-y-conocimientos.md
> +- Cada miembro del departamento es conscientes de los distintos niveles de conocimiento en cada miembro. Asegurando el desarrollo de todos los miembros se pueden aplicar las siguientes estrategias:
hay una "s" de más en conscientes

2020-10-21 22:01 UTC, DanElias commented on Politica-de-gestion-habilidades-y-conocimientos.md
> + -- Recopilación de información relevante para abordar problemas, logrando acuerdos que fomenten la confianza en el equipo.
se murieron los bullet points del markdown y salen solo rallitas 😢

2020-10-21 22:01 UTC, DanElias commented on _Sidebar.md
> +* [\[POL18\] Política de gestión de habilidades y conocimientos](https://github.com/novaDepto/Nova/wiki/Politica-de-gestion-habilidades-y-conocimientos)
Hay conflicto en la numeración, pero ahorita solo hay que quitarlo y ya Ray le va a poner bien la numeración a la sidebar

2020-10-22 02:31 UTC, DanElias approved these changes

2020-10-22 15:53 UTC, Raylogic approved these changes

2020-10-22 15:53 UTC, merged

2020-10-22 16:03 UTC, ErwinJulian commented on Politica-de-gestion-habilidades-y-conocimientos.md
> +        <li>ERecopilación de información relevante para abordar problemas, logrando acuerdos que fomenten la confianza en el equipo.</li>
Creo que se te fue una E, dice "ERecopilación"

2020-10-22 16:03 UTC, ErwinJulian commented on Politica-de-gestion-habilidades-y-conocimientos.md
> +- Los miembros del departamento siguen las prácticas de dirección de conflictos y contribuyen en su mejora, cómo factor para la reducción de conflictos.
este "cómo"  creo que no lleva acento