Update Proceso-de-asignación-de-roles.md
novaDepto/Nova pull request #90
Opened 2020-10-22 11:47 UTC by Raylogic

2020-10-22 17:41 UTC, marlagr approved these changes

2020-10-22 18:34 UTC, ErwinJulian commented on Proceso-de-asignación-de-roles.md
>    <thead>
Tal vez pondría ya las acciones concretas para decidir, por ejemplo, en caso de solo haber un postulante: pasa directamente a tomar el rol, y en caso de haber 2 o más postulantes se procede a una votación por poll a todo el departamento donde cada persona explica sus objetivos y metas, y del por qué haría un buen papel

2020-10-23 17:19 UTC, ErwinAndresJL requested changes

2020-10-23 17:19 UTC, ErwinAndresJL commented on Proceso-de-asignación-de-roles.md
>  ## Proceso
En esta parte de proceso, definiría de una vez aquí el cómo se pondrían de acuerdo en caso de haber 2 o más interesados en el rol.

2020-10-27 04:50 UTC, DanElias commented on Proceso-de-asignación-de-roles.md
>  ## Proceso
Hay que quitar esto de políticas y estándares

2020-10-28 21:53 UTC, closed without merging